"""Add child recipient relation

Revision ID: 8665129c1122
Revises: 8ad5fc527484
Create Date: 2016-09-14 12:06:10.309051

"""

# revision identifiers, used by Alembic.
revision = '8665129c1122'
down_revision = '8ad5fc527484'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.uuid


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
    	batch_op.add_column(sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True))
    	batch_op.create_foreign_key(op.f('fk_recipient_parent_id_recipient'), 'recipient', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
    	batch_op.drop_constraint(op.f('fk_recipient_parent_id_recipient'), type_='foreignkey')
    	batch_op.drop_column('parent_id')
    ### end Alembic commands ###
